import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useUser, withPageAuthRequired } from '@auth0/nextjs-auth0';
import prisma from '../../../lib/prisma';
// Function below requires auth

function currentUser(auth0User){
  if(auth0User){
    const getUser = prisma.User.findUnique({
      where: {
        email: auth0User.email,
      }})
      //check if user is in db, if not add it
    if(getUser != null){
        let currentUser = getUser
            console.log(currentUser)
            
    }
    else{
      const newUser = prisma.User.create({
        data: {
          email: auth0User.email
        }})
    //save user to session when working
      let currentUser = newUser
      console.log(currentUser)
      }
        }
      }




export default withPageAuthRequired(MyProfile);

function MyProfile(){
  // user object from Auth0
  const { user, isLoading } = useUser();
  currentUser(user)
  // const currentUser = async (user) => {
  //   fetch('http://localhost:3000/api/auth/currentUser',{
  //     body: JSON.stringify(user),
  //     method: 'POST',
  //   })
  // }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My Profile Page</a>
        </h1>
        <h1 className={styles.title}>
          {user.email}
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
