import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import prisma from '/lib/prisma';
import { useUser, withPageAuthRequired } from '@auth0/nextjs-auth0';

// Function below requires auth
export default withPageAuthRequired(MyProfile);

function MyProfile(){
  // user object from Auth0
  const { user, isLoading } = useUser();

  // add current user when next-session is working
  if(user){
    const getUser = prisma.User.findUnique({
      where: {
        id: user.email,
      }
    })
    //check if user is in db, if not add it
    if(getUser != null){
      let currentUser = getUser
      //save user to session when working
    }
    else{
      const newUser = prisma.User.create({
        data: {
          email: user.email
        }
       })
       //save user to session when working
       let currentUser = newUser
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My Profile Page</a>
        </h1>
        <h1 className={styles.title}>
          {user.email}
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
